# Generated by Django 6.0.5 on 2026-05-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_aboutbanner_aboutsection_gallery_album_gallerybanner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='twitter',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactsection',
            name='description',
            field=models.TextField(max_length=112),
        ),
    ]
