# Generated by Django 6.0.5 on 2026-05-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_contactinfo_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
