# Generated by Django 6.0.5 on 2026-05-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_contactinfo_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmap',
            name='map_lat',
        ),
        migrations.RemoveField(
            model_name='contactmap',
            name='map_lng',
        ),
        migrations.RemoveField(
            model_name='contactmap',
            name='map_marker_json',
        ),
        migrations.RemoveField(
            model_name='contactmap',
            name='map_zoom',
        ),
        migrations.AddField(
            model_name='contactmap',
            name='map_embed_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
