# Generated by Django 6.0.5 on 2026-05-07 11:24

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Team', max_length=100)),
                ('banner_image', models.ImageField(upload_to='team/banner/', validators=[backend.models.validate_banner_image])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
