# Generated by Django 6.0.5 on 2026-05-07 11:41

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_teambanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBusinessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(default='Our Business', max_length=100)),
                ('title', models.CharField(default='Stand Out From The Rest', max_length=180)),
                ('top_image', models.ImageField(upload_to='about/business/', validators=[backend.models.validate_about_business_image])),
                ('bottom_image', models.ImageField(upload_to='about/business/', validators=[backend.models.validate_about_business_image])),
                ('core_title', models.CharField(default='Our Core Values', max_length=120)),
                ('core_description', models.TextField(max_length=150)),
                ('core_values', models.TextField(help_text='Enter one value per line.')),
                ('mission_title', models.CharField(default='Our Mission', max_length=120)),
                ('mission_description', models.TextField(max_length=150)),
                ('vision_title', models.CharField(default='Our Vision', max_length=120)),
                ('vision_description', models.TextField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(default='We are', max_length=100)),
                ('title', models.CharField(default='Leaders in HR Solution', max_length=180)),
                ('badge_text', models.CharField(default='Since 1998, Operating in Birmingham.', max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('main_image', models.ImageField(upload_to='about/hero/', validators=[backend.models.validate_about_hero_image])),
                ('video_thumbnail', models.ImageField(upload_to='about/hero/', validators=[backend.models.validate_about_hero_image])),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=100)),
                ('banner_image', models.ImageField(upload_to='about/banner/', validators=[backend.models.validate_banner_image])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutBanner',
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
    ]
