# Generated by Django 6.0.5 on 2026-05-07 11:52

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_aboutbusinesssection_aboutherosection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutherosection',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='about/videos/', validators=[backend.models.validate_about_video_file]),
        ),
    ]
