# Generated by Django 6.0.5 on 2026-05-09 05:27

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_aboutherosection_badge_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFavicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='favicons/', validators=[backend.models.validate_website_brand_image])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(upload_to='logos/', validators=[backend.models.validate_website_brand_image]),
        ),
    ]
