# Generated by Django 6.0.5 on 2026-05-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_websitefavicon_alter_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutherosection',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
