# Generated by Django 6.0.5 on 2026-05-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_aboutherosection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutherosection',
            name='short_description',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='aboutherosection',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
