# Generated by Django 6.0.5 on 2026-05-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_aboutherosection_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutherosection',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutherosection',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
