# Generated by Django 6.0.5 on 2026-05-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_aboutherosection_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutherosection',
            name='short_description',
        ),
    ]
