# Generated by Django 6.0.5 on 2026-05-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_homeaboutmedia_homebanner_homefaqitem_homefaqsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='description_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='subtitle_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='title_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
