# Generated by Django 6.0.5 on 2026-05-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_homebanner_description_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='subtitle',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
