# Generated by Django 6.0.5 on 2026-05-09 10:35

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_homebanner_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sisterconcern',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='sister_concerns/images/', validators=[backend.models.validate_sister_concern_display_image]),
        ),
    ]
