# Generated by Django 6.0.5 on 2026-05-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_sisterconcern_display_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='We Offer Different Services', max_length=120)),
                ('description', models.CharField(default='There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form believable.', max_length=180)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
