# Generated by Django 6.0.5 on 2026-05-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_homeservicesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryBanner',
        ),
    ]
