# Generated by Django 6.0.5 on 2026-05-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_aboutherosection_id_alter_aboutpagebanner_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWhyChooseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=180)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='home/why_choose/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeWhyChooseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(default='CHOICES & OCCURS', max_length=80)),
                ('title', models.CharField(default='Why People Choose us', max_length=120)),
                ('description', models.CharField(default='Explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system.', max_length=220)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sisterconcern',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sister_concerns/logos/'),
        ),
    ]
