# Generated by Django 6.0.5 on 2026-05-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_homewhychooseitem_homewhychoosesection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewhychooseitem',
            name='description',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='homewhychooseitem',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
