# Generated by Django 6.0.5 on 2026-05-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_homewhychooseitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewhychoosesection',
            name='description',
            field=models.CharField(default='Explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system.', max_length=120),
        ),
        migrations.AlterField(
            model_name='homewhychoosesection',
            name='title',
            field=models.CharField(default='Why People Choose us', max_length=20),
        ),
    ]
