# Generated by Django 6.0.5 on 2026-05-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_homewhychoosesection_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBusinessItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=120)),
                ('icon_class', models.CharField(default='icon-bow-and-arrow', max_length=60)),
                ('value_lines', models.TextField(blank=True, default='', help_text='Optional. Add one value per line.', max_length=220)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeBusinessSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(default='Our Business', max_length=30)),
                ('title', models.CharField(default='Stand Out From The Rest', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
