# Generated by Django 6.0.5 on 2026-05-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_homebusinessitem_homebusinesssection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebusinessitem',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='homebusinessitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='home/business/'),
        ),
    ]
