# Generated by Django 6.0.5 on 2026-05-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_remove_homebusinessitem_icon_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebusinessitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='homebusinessitem',
            name='value_lines',
            field=models.TextField(blank=True, default='', help_text='For the middle Core Values card only. Add one value per line, max 6 lines.', max_length=300),
        ),
    ]
