# Generated by Django 6.0.5 on 2026-05-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_homebusinessitem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHeaderSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_message', models.CharField(default='Welcome to our consulting company.', max_length=80)),
                ('quote_button_text', models.CharField(default='Get a quote', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
