# Generated by Django 6.0.5 on 2026-05-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_siteheadersetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutherosection',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='homeaboutmedia',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
    ]
