# Generated by Django 5.2.8 on 2026-05-12 08:43

import json
import backend.models
import django.db.models.deletion
from django.conf import settings
from django.core.files.storage import default_storage
from django.db import migrations, models
from pathlib import Path


def migrate_json_gallery(apps, schema_editor):
    SisterConcern = apps.get_model('backend', 'SisterConcern')
    GalleryImage = apps.get_model('backend', 'SisterConcernGalleryImage')
    gallery_store = Path(settings.BASE_DIR) / "backend" / "sister_concern_gallery.json"
    if not gallery_store.exists():
        return

    try:
        data = json.loads(gallery_store.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return

    if not isinstance(data, dict):
        return

    for concern_id, paths in data.items():
        if not SisterConcern.objects.filter(pk=concern_id).exists():
            continue
        if not isinstance(paths, list):
            continue
        for index, image_path in enumerate(paths, start=1):
            if not image_path:
                continue
            try:
                exists = default_storage.exists(image_path)
            except (OSError, ValueError):
                exists = False
            if not exists:
                continue
            GalleryImage.objects.get_or_create(
                sister_concern_id=concern_id,
                image=image_path,
                defaults={"sort_order": index},
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_remove_aboutherosection_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SisterConcernGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sister_concerns/gallery/', validators=[backend.models.validate_sister_concern_display_image])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sister_concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='backend.sisterconcern')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(migrate_json_gallery, noop_reverse),
    ]
