# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0038_sisterconcerngalleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homebanner",
            name="description",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="homebanner",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="homebanner",
            name="title",
            field=models.CharField(blank=True, default="", max_length=25),
        ),
        migrations.AlterField(
            model_name="homewhychooseitem",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.RemoveField(
            model_name="homewhychooseitem",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="aboutherosection",
            name="badge_image",
        ),
        migrations.AddField(
            model_name="siteheadersetting",
            name="footer_description",
            field=models.CharField(
                blank=True,
                default="Over 20 years of experience we'll ensure you always get the best guidance. We serve clients at every level of their organization...",
                max_length=150,
            ),
        ),
    ]
