# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0039_home_banner_why_choose_footer_about_cleanup"),
    ]

    replaces = [
        ("backend", "0040_alter_homewhychoosesection_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homewhychoosesection",
            name="description",
            field=models.CharField(
                default="Explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system.",
                max_length=120,
            ),
        ),
    ]
