# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0040_keep_homewhychoosesection_description_120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homewhychooseitem",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
