# Generated by Django 6.0.5 on 2026-05-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_alter_homewhychooseitem_description_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewhychooseitem',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
