# Generated by Django 6.0.5 on 2026-05-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_alter_homewhychooseitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewhychooseitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
