# Generated by Django 6.0.5 on 2026-05-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_fromdata',
        ),
        migrations.DeleteModel(
            name='Contact_Location',
        ),
        migrations.DeleteModel(
            name='Contact_Schedule',
        ),
        migrations.DeleteModel(
            name='ContactBanner',
        ),
    ]
