# Generated by Django 6.0.5 on 2026-05-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_delete_contact_fromdata_delete_contact_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutBanner',
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.RemoveField(
            model_name='gallery_albumdetails',
            name='album',
        ),
        migrations.DeleteModel(
            name='GalleryBanner',
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.DeleteModel(
            name='SisterConcern',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Gallery_Album',
        ),
        migrations.DeleteModel(
            name='Gallery_AlbumDetails',
        ),
    ]
